### ISSUE TITLE
DELETE being issued on quiz_templates url without a quiz id

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-quiz#177]
Noticed this in the logs.  Maybe the admin grid client is sending a DELETE without a quiz_id if nothing if no quiz is selected?

```
, [2016-05-17T04:32:03.865233 #653]  INFO -- : Processing by QuizTemplatesController#destroy as */*
I, [2016-05-17T04:32:03.866108 #653]  INFO -- :   Parameters: {"{}"=>nil, "course_id"=>"01005", "quiz_id"=>"1507"}
I, [2016-05-17T04:32:03.883476 #653]  INFO -- : Deleting 1507
I, [2016-05-17T04:32:03.884334 #653]  INFO -- : GIT_SSH_COMMAND='ssh  -o StrictHostKeyChecking=no -i /dtu-quiz/app/dtu-data/keys/01005'
I, [2016-05-17T04:32:03.884525 #653]  INFO -- : Deleting Q1507.quiz
I, [2016-05-17T04:32:03.884716 #653]  INFO -- : Starting Git
I, [2016-05-17T04:32:03.902678 #653]  INFO -- : git '--git-dir=/dtu-quiz/app/dtu-data/01005/.git' '--work-tree=/dtu-quiz/app/dtu-data/01005' config 'user.name' 'Iain Bryson Admin [from DTU quiz]'  2>&1
D, [2016-05-17T04:32:03.902912 #653] DEBUG -- : 
I, [2016-05-17T04:32:03.921665 #653]  INFO -- : git '--git-dir=/dtu-quiz/app/dtu-data/01005/.git' '--work-tree=/dtu-quiz/app/dtu-data/01005' config 'user.email' 'bryson.iain@gmail.com'  2>&1
D, [2016-05-17T04:32:03.921887 #653] DEBUG -- : 
I, [2016-05-17T04:32:03.941979 #653]  INFO -- : git '--git-dir=/dtu-quiz/app/dtu-data/01005/.git' '--work-tree=/dtu-quiz/app/dtu-data/01005' rm '-f' '--' 'Q1507.quiz'  2>&1
D, [2016-05-17T04:32:03.942202 #653] DEBUG -- : rm 'Q1507.quiz'
I, [2016-05-17T04:32:03.963074 #653]  INFO -- : git '--git-dir=/dtu-quiz/app/dtu-data/01005/.git' '--work-tree=/dtu-quiz/app/dtu-data/01005' commit '--message=Deleting quiz file'  2>&1
D, [2016-05-17T04:32:03.963302 #653] DEBUG -- : [master 1d3d82f] Deleting quiz file
 1 file changed, 85 deletions(-)
 delete mode 100644 Q1507.quiz
I, [2016-05-17T04:32:06.479316 #653]  INFO -- : git '--git-dir=/dtu-quiz/app/dtu-data/01005/.git' '--work-tree=/dtu-quiz/app/dtu-data/01005' push 'origin' 'master'  2>&1
D, [2016-05-17T04:32:06.479520 #653] DEBUG -- : To git@github.com:dtu-compute/01005.git
   a9bc6ae..1d3d82f  master -> master
I, [2016-05-17T04:32:06.489692 #653]  INFO -- : {:success=>true, :message=>"Succeeded in deleting Q1507"}
I, [2016-05-17T04:32:06.490738 #653]  INFO -- : Completed 200 OK in 2624ms (Views: 0.6ms)
I, [2016-05-17T04:32:06.493870 #653]  INFO -- : Started DELETE "/courses/01005/quiz_templates" for 213.55.105.121 at 2016-05-17 04:32:06 +0000
F, [2016-05-17T04:32:06.496463 #653] FATAL -- : 
ActionController::RoutingError (No route matches [DELETE] "/courses/01005/quiz_templates"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  faye-websocket (0.10.0) lib/faye/adapters/thin.rb:40:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  faye-websocket (0.10.0) lib/faye/adapters/thin.rb:44:in `receive_data'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run_machine'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  thin (1.6.4) lib/thin/controllers/controller.rb:87:in `start'
  thin (1.6.4) lib/thin/runner.rb:200:in `run_command'
  thin (1.6.4) lib/thin/runner.rb:156:in `run!'
  thin (1.6.4) bin/thin:6:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<main>'


I, [2016-05-17T04:32:07.115022 #653]  INFO -- : Started GET "/courses/01005/quiz_templates/?utf8=%E2%9C%93" for 213.55.105.121 at 2016-05-17 04:32:07 +0000
I, [2016-05-17T04:32:07.116924 #653]  INFO -- : Processing by QuizTemplatesController#index as */*
I, [2016-05-17T04:32:07.117062 #653]  INFO -- :   Parameters: {"utf8"=>"✓", "course_id"=>"01005"}
I, [2016-05-17T04:32:07.141035 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (2.5ms)
I, [2016-05-17T04:32:07.144873 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (1.7ms)
I, [2016-05-17T04:32:07.147481 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (2.0ms)
I, [2016-05-17T04:32:07.150513 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (2.1ms)
I, [2016-05-17T04:32:07.153172 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (1.7ms)
I, [2016-05-17T04:32:07.155689 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (1.4ms)
I, [2016-05-17T04:32:07.157736 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (1.3ms)
I, [2016-05-17T04:32:07.159695 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_order_for.html.erb (1.3ms)
I, [2016-05-17T04:32:07.161704 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_head.html.erb (24.6ms)
I, [2016-05-17T04:32:07.214620 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (4.5ms)
I, [2016-05-17T04:32:07.217278 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.2ms)
I, [2016-05-17T04:32:07.219988 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.4ms)
I, [2016-05-17T04:32:07.222329 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.0ms)
I, [2016-05-17T04:32:07.224793 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.1ms)
I, [2016-05-17T04:32:07.227833 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.7ms)
I, [2016-05-17T04:32:07.230170 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.0ms)
I, [2016-05-17T04:32:07.232710 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.2ms)
I, [2016-05-17T04:32:07.235348 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.3ms)
I, [2016-05-17T04:32:07.237949 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.2ms)
I, [2016-05-17T04:32:07.240220 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (1.9ms)
I, [2016-05-17T04:32:07.242784 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.3ms)
I, [2016-05-17T04:32:07.245218 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.1ms)
I, [2016-05-17T04:32:07.247608 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.0ms)
I, [2016-05-17T04:32:07.250314 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.2ms)
I, [2016-05-17T04:32:07.252710 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.0ms)
I, [2016-05-17T04:32:07.255227 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.2ms)
I, [2016-05-17T04:32:07.257604 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.0ms)
I, [2016-05-17T04:32:07.259916 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.0ms)
I, [2016-05-17T04:32:07.262629 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.4ms)
I, [2016-05-17T04:32:07.265046 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.1ms)
I, [2016-05-17T04:32:07.267939 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.4ms)
I, [2016-05-17T04:32:07.270351 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.1ms)
I, [2016-05-17T04:32:07.272729 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.0ms)
I, [2016-05-17T04:32:07.275679 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_row.html.erb (2.6ms)
I, [2016-05-17T04:32:07.276611 #653]  INFO -- :   Rendered /usr/local/share/gems/gems/datagrid-1.4.3/app/views/datagrid/_table.html.erb (140.0ms)
I, [2016-05-17T04:32:07.282838 #653]  INFO -- : Completed 200 OK in 166ms (Views: 5.9ms)
I, [2016-05-17T04:32:13.330355 #653]  INFO -- : Started GET "/courses/01005/quiz_templates/update/1513" for 213.55.105.121 at 2016-05-17 04:32:13 +0000
I, [2016-05-17T04:32:13.332865 #653]  INFO -- : Processing by QuizTemplatesController#update_quiz as JS
I, [2016-05-17T04:32:13.333017 #653]  INFO -- :   Parameters: {"course_id"=>"01005", "quiz_id"=>"1513"}
I, [2016-05-17T04:32:13.386240 #653]  INFO -- :   Rendered quiz_templates/_quiz_form.html.erb (20.9ms)
I, [2016-05-17T04:32:13.389304 #653]  INFO -- :   Rendered quiz_templates/update_quiz.js.erb (26.7ms)
I, [2016-05-17T04:32:13.389811 #653]  INFO -- : Completed 200 OK in 57ms (Views: 35.8ms)
```

**Comment by iainbryson** [comment]
If this shows up again we can investigate it; otherwise I don't think there's a way to figure out what's up.
