### ISSUE TITLE
Take quiz button not responding

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#220]
One of the professors had two students that couldn't take one of the quizzes more than once even thought they student had 49 attempts left. The quiz button for entering the quiz didn't respond.

One of the students were s153229 and it happened on the 31th of January.

Can your newly developed client side JavaScript error logged be used for this? 

<img width="989" alt="skaermbillede 2017-01-31 16 34 02" src="https://cloud.githubusercontent.com/assets/13518486/22522401/bfa48980-e8bb-11e6-971b-2d1acc0a6c2f.png">

**Comment by dtu-compute** [comment]
The two students above were both Mac users, but a third on Windows had also been spotted with this issue somewhere between 16:38 and 16:49 CET. The Windows student hadn't taken the quiz at all, but still couldn't take it.

**Comment by iainbryson** [comment]
I performed some analysis on the logs (for future reference, I did `grep -n -B 3 -A 3 s153229 production.log` on `/vol/log/quiz/production.log` if you ever want to do something similar)

What I found seems to "almost" match with what you describe.

Around the right time, there's this:

```
W, [2017-01-31T15:56:37.736784 #662]  WARN -- : User #<DTUAuth2::User2:0x007f58a5f5a5f0 @_id="s164556", @full_name="Jacob Tobias Lindberg", @email="s164556@student.dtu.dk"> in groups ^[[0;31;49mnil^[[0m is not able to take quiz #<QuizTemplate _id: 588974074d8baa029682c1f5, course_id: "02402", quiz_creator_id: nil, quiz_name: "Exercise Week1 (1 question)", quiz_creator_name: nil, quiz_creator_email: nil, quiz_path: "Q29.quiz", quiz_number: 29, cloned_from_quiz_number: nil, start_time(datetime): 2017-01-20 13:18:00 UTC, end_time(datetime): 2017-06-01 13:18:00 UTC, max_time: nil, feedback_before: 2, feedback_after: 2, group_names: ["Main"], visible_to_students: true, was_visible_to_students: false, compile_status: "OK", last_compile_attempt_time: 2017-01-26 20:31:11 UTC, attempts: 50, full_screen: false, add_dont_know: false, quiz_errors: [], quiz_loaded_commit: "759f59921f9e9ef78437ecc9b57af921979899d9", quiz_repo_commit: nil, stats_recomputed_time: 2017-01-20 16:18:50 UTC, total_submissions_created: 62, total_handed_in: 56, total_unique_student_submissions_created: 58, total_unique_student_handed_in: 53, eligeable_students: ["s170279", "s166127", "s166103", "s166087", "s166112", "s166114", "s164395", "s164571", "s164567", "s166390", "s170307", "s166340", "s170435", "s164322", "s164424", "s164024", "s166454", "s164568", "s170243", "s143880", "s154272", "s163053", "s164398", "s164410", "s164419", "s144367", "s151259", "s163923", "s164431", "s133645", "s133720", "s164566", "s144517", "s154043", "s133604", "s152999", "s154028", "s164443", "s143605", "s164577", "s166329", "s166408", "s153402", "s151712", "s161721", "s166339", "suslin", "s162217", "s153651", "s143911", "s166251", "s133622", "s143895", "s143885", "s154123", "s123636", "s133620", "s164434", "s164402", "s164403", "s153479", "s154077", "stefhan", "s152369", "s150160", "s146992", "s154071", "s164436", "s161710", "s163740", "s124923", "s154165", "s164534", "s164530", "s153568", "s164407", "s164541", "s154239", "s164546", "s164529", "s164532", "s124330", "s164539", "s165317", "s166245", "s164542", "s164547", "s164544", "s164422", "s164536", "s121840", "s141361", "s153229", "s166249", "s164533", "s164537", "s154209", "s164433", "s164551", "s153724", "s164561", "s144524", "s164564", "phiho", "s164440", "s160081", "s163450", "s164428", "s164418", "s164565", "s165498", "s164563", "s154099", "s154214", "s164429", "s143493", "s164531", "s164574", "s144134", "s137320", "s111625", "s153794", "s153350", "s153281", "s153298", "s164397", "s144158", "s127789", "s141022", "s143958", "s143982", "s130332", "s165514", "s164569", "s162105", "s170362", "s164578", "s161696", "s143876", "s164587", "s165318", "s165540", "s154156", "s161794", "s124347", "s164432", "s130733", "s133263", "s144028", "s144066", "s122693", "s143898", "s165316", "s153021", "s143887", "s164572", "s164409", "s164525", "s153509", "s134855", "s134752", "s164557", "s164527", "s164540", "s134644", "s153871", "s134261", "s133195", "s151760", "s164535", "s143823", "s143861", "s164556", "s164586", "s153234", "s165517", "s144126", "s154308", "s154407", "s164399", "s151941", "s164425", "s144350", "s022518", "s153133", "s144002", "s164401", "s125096", "s143231", "s143906", "s164413", "s144510", "s164438", "s102261", "s143933", "s155613", "s144507", "s154267", "s144514", "s154060", "s153955", "s164582", "s164394", "s154101", "s164412", "s164559", "s153360", "s144373", "s143874", "s162158", "s133260", "s154680", "s164423", "s133198", "s164584", "s151632", "s144168", "s154356", "s164560", "s141043", "s164548", "s164555", "s164580", "s153171", "s143948", "s164545", "s134787", "s164408", "s153380", "s134737", "s132316", "s134398", "s165489", "s153126", "s164442", "s165315", "s135096", "s153282", "matlin", "s154654", "s143971", "s143968", "s154232", "s144204", "s154203", "s144121", "s123276", "s164543", "s144093", "s153678", "phikro", "s164445", "s145786", "s164575", "s113330", "s161699", "s153716", "s143367", "s144125", "s151746", "s153520", "s121914"], total_eligeable_students: 262, total_needs_review: 0, total_reviewable_questions: 0>
I, [2017-01-31T15:56:37.740747 #662]  INFO -- : Completed 500 Internal Server Error in 11ms
F, [2017-01-31T15:56:37.741962 #662] FATAL -- :
NameError (undefined local variable or method `group' for #<NewQuizInstanceService:0x007f5888246278>):
  app/services/new_quiz_instance_service.rb:46:in `explain_why_user_can_take_quiz'
  app/controllers/new_quiz_controller.rb:29:in `view'

```

This seems like a simple typo bug explaining why the student can't take the quiz (because there's a quiz in progress.)  Because of that we can't tell exactly why they're not allowed to take the quiz.  As far as the client is concerned, there are no ongoing quizzes:

```
I, [2017-01-31T15:56:37.673925 #662]  INFO -- : CLIENT DEBUG from #<DTUAuth2::User2:0x007f58907fe410 @_id="s164556", @full_name="Jacob Tobias Lindberg", @email="s164556@student.dtu.dk"> Found no in-progress quizzes for Q29
```


Is s164556 the second student?

It looks like s153229 was has a successful hand-in on 30/1, but thereafter didn't have any serious error logs:

```
367091:I, [2017-01-30T20:05:59.093380 #662]  INFO -- : Quiz handed in by s153229 (s153229): #<QuizInstance _id: 588f9b064d8baa029682e5ac, created_at: 2017-01-30 19:59:02 UTC, updated_at: 2017-01-30 20:05:59 UTC, user_id: "s153229", group_id: "Main", course_id: "02402", quiz_id: BSON::ObjectId('588a5ba04d8baa029682d584'), group_name: "Main", user_name: "Helena Haarup Lauritzen", user_email: "s153229@student.dtu.dk", quiz_name: "Test week 1 (5 questions)", quiz_number: 43, submission_id: 113, attempt_no: 0, max_attempt_no: 50, start_time(datetime): 2017-01-16 18:53:00 UTC, quiz_end_time(datetime): 2017-05-31 18:53:00 UTC, instance_end_time(datetime): 2017-05-31 18:53:00 UTC, first_view_time(datetime): 2017-01-30 19:59:04 UTC, last_edit_time(datetime): 2017-01-30 20:05:51 UTC, first_edit_time(datetime): 2017-01-30 19:59:54 UTC, create_time(datetime): 2017-01-30 19:59:02 UTC, max_time: nil, time_used: 0, handed_in: true, handed_in_time(datetime): 2017-01-30 20:05:59 UTC, remaining_to_be_scored: nil, feedback_before: 2, feedback_after: 2, needs_review_count: 0, max_needs_review_count: 0, ips_seen: {"82,211,206,85"=>1}, useragents_seen: {"Mozilla/5,0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/602,3,12 (KHTML, like Gecko) Version/10,0,2 Safari/602,3,12"=>1}, full_screen: false, add_dont_know: false, times_entered_fullscreen: [], times_exited_fullscreen: []>
367092-I, [2017-01-30T20:05:59.094500 #662]  INFO -- :   Rendered quiz_handed_in/view.html.erb within layouts/application (0.5ms)
```

There was also this fatal issue:

```
444556-I, [2017-01-31T15:34:57.157983 #662]  INFO -- : Completed 500 Internal Server Error in 4ms
444557:F, [2017-01-31T15:34:57.158866 #662] FATAL -- : 
444558-NoMethodError (undefined method `[]' for nil:NilClass):
444559-  app/controllers/student_quizzes_controller.rb:43:in `current_groups'
444560-  app/controllers/student_quizzes_controller.rb:28:in `checksum'
```


Which I'll add additional logging around.
