### ISSUE TITLE
prod: Edit Meta have stopped working

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-quiz#50]
For 01005 on prod. server he reported that when he created a new quiz, and clicked Edit Meta on that, he got the meta info from the other quiz. But right now he and I don't get the modal at all.

**Comment by iainbryson** [comment]
Interesting.  From the logs it appears that this is related having no max_time:

```
F, [2016-04-08T12:17:37.932111 #352] FATAL -- :
ActionView::Template::Error (undefined method `%' for nil:NilClass):
    37:                   <div class="col-md-8">
    38:                   <%= f.check_box :"max_time?", {:checked => @new_quiz_template.max_time == nil} %> Unlimited Time
    39:                   <br/>
    40:                   <%= f.select(:max_time_days, (0..30).to_a.map{|h| [h.to_s, h]}, {}, {:class => "max_time_duration_component"})  %>
    41:                   <span> days </span>
    42:                   <%= f.select(:max_time_hours, (0..23).to_a.map{|h| [h.to_s, h]}, {}, {:class => "max_time_duration_component"})  %>
    43:                   <span> hours </span>
  app/models/quiz_template.rb:81:in `max_time_days'
  app/views/quiz_templates/_quiz_form.html.erb:40:in `block in _app_views_quiz_templates__quiz_form_html_erb___269517663385508214_47006809802600'
  app/views/quiz_templates/_quiz_form.html.erb:8:in `_app_views_quiz_templates__quiz_form_html_erb___269517663385508214_47006809802600'
  app/views/quiz_templates/update_quiz.js.erb:3:in `_app_views_quiz_templates_update_quiz_js_erb__982899758408935053_47006826394800'
  app/controllers/quiz_templates_controller.rb:101:in `update_quiz'

```

Which is a new symptom of the old issue.  Did you try to create a new quiz and edit its metadata also?

**Comment by dtu-compute** [comment]
Just created a new quiz Q1433, and you are right. When not using unlimited time, then I can Edit Meta, when I set Unlimited Time, Edit Meta doesn't work.
